### ISSUE TITLE
Talk on speech recognition in ROS

### ISSUE THREAD

**Issue by Pankaj-Baranwal** [rospijam/talks#1]
**Abstract (2-3 lines)**
With voice-based assistants like Siri, Google Now and Cortana trying to befriend us, open source speech recognition based assistant is the need of the hour! So, this talk will be about similar such effort for providing offline, lightweight speech recognition abilities in ROS
**Brief Description and Contents to be covered**
Topics to be covered:
1) Basic speech recognition concepts
2) Keyword spotting mode in pocketsphinx
3) Grammar mode in pocketsphinx
4) Okay Google mode
5) Hands-on demonstration
6) How to develop new applications based on pocketsphinx
7) What else is out there?  

**Pre-requisites for the talk**
Basic knowledge of ROS and catkin workspace
**Time required for the talk**
35 minutes
**Link to slides**
No link. Yet.
**Will you be doing hands-on demo as well?**
Yes
**About yourself**
ROS enthusiast. Been working with CMUSphinx from past 6 months.
**Are you comfortable if the talk is recorded and uploaded to PyData Delhi's YouTube channel ?**
PyData? I thought I was going to ROSPi meetup. Anyways, no problem.
**Any query ?**
Am I the only one?

**Comment by Ridhwanluthra** [comment]
This template was adapted from the issue format by pydata. Thanks for pointing out the error.
